// AI Startup Funding Data
// This provides curated funding data for the startup tracker

export type FundingRound = {
  id: string;
  company: string;
  logo?: string;
  description: string;
  amount: string; // e.g., "$1B", "$500M"
  amountNum: number; // For sorting, in millions
  round: string; // "Series A", "Series B", "Seed", etc.
  date: string; // ISO date
  investors: string[];
  category: string; // "Foundation Models", "AI Infrastructure", "AI Applications", etc.
  valuation?: string;
  website?: string;
  headquarters: string;
};

export const FUNDING_CATEGORIES = [
  'Foundation Models',
  'AI Infrastructure',
  'AI Applications',
  'AI Agents',
  'AI Hardware',
  'AI Safety',
  'Healthcare AI',
  'Enterprise AI',
  'Robotics',
  'Autonomous Vehicles',
] as const;

export const ROUND_TYPES = [
  'Seed',
  'Series A',
  'Series B',
  'Series C',
  'Series D',
  'Series E+',
  'Growth',
  'Debt',
  'Acquisition',
] as const;

// Curated AI funding rounds - updated regularly
export const FUNDING_ROUNDS: FundingRound[] = [
  // 2024 Major Rounds
  {
    id: 'xai-series-c-2024',
    company: 'xAI',
    description: 'Elon Musk\'s AI company building Grok and competing with OpenAI',
    amount: '$6B',
    amountNum: 6000,
    round: 'Series C',
    date: '2024-12-01',
    investors: ['a16z', 'Sequoia Capital', 'Valor Equity Partners', 'Kingdom Holdings'],
    category: 'Foundation Models',
    valuation: '$50B',
    website: 'https://x.ai',
    headquarters: 'Palo Alto, CA',
  },
  {
    id: 'openai-2024',
    company: 'OpenAI',
    description: 'Creator of ChatGPT and GPT-4, leading AI research lab',
    amount: '$6.6B',
    amountNum: 6600,
    round: 'Growth',
    date: '2024-10-02',
    investors: ['Thrive Capital', 'Microsoft', 'NVIDIA', 'SoftBank', 'Khosla Ventures'],
    category: 'Foundation Models',
    valuation: '$157B',
    website: 'https://openai.com',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'anthropic-series-e-2024',
    company: 'Anthropic',
    description: 'AI safety company building Claude, focused on interpretable AI',
    amount: '$4B',
    amountNum: 4000,
    round: 'Series E+',
    date: '2024-03-01',
    investors: ['Amazon', 'Google', 'Spark Capital', 'Salesforce Ventures'],
    category: 'Foundation Models',
    valuation: '$18B',
    website: 'https://anthropic.com',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'databricks-series-j-2024',
    company: 'Databricks',
    description: 'Data and AI platform unifying analytics, data engineering, and ML',
    amount: '$10B',
    amountNum: 10000,
    round: 'Series J',
    date: '2024-12-01',
    investors: ['Thrive Capital', 'a16z', 'DST Global', 'GIC', 'Insight Partners'],
    category: 'AI Infrastructure',
    valuation: '$62B',
    website: 'https://databricks.com',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'scale-ai-series-f-2024',
    company: 'Scale AI',
    description: 'AI data platform providing training data and evaluation for AI models',
    amount: '$1B',
    amountNum: 1000,
    round: 'Series F',
    date: '2024-05-01',
    investors: ['Accel', 'Amazon', 'Meta', 'Intel Capital'],
    category: 'AI Infrastructure',
    valuation: '$14B',
    website: 'https://scale.com',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'perplexity-series-b-2024',
    company: 'Perplexity',
    description: 'AI-powered answer engine and search platform',
    amount: '$500M',
    amountNum: 500,
    round: 'Series B',
    date: '2024-12-01',
    investors: ['IVP', 'NEA', 'Databricks Ventures', 'NVIDIA'],
    category: 'AI Applications',
    valuation: '$9B',
    website: 'https://perplexity.ai',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'mistral-series-b-2024',
    company: 'Mistral AI',
    description: 'European AI lab building open-weight foundation models',
    amount: '$640M',
    amountNum: 640,
    round: 'Series B',
    date: '2024-06-01',
    investors: ['General Catalyst', 'a16z', 'Lightspeed', 'BNP Paribas'],
    category: 'Foundation Models',
    valuation: '$6B',
    website: 'https://mistral.ai',
    headquarters: 'Paris, France',
  },
  {
    id: 'cohere-series-d-2024',
    company: 'Cohere',
    description: 'Enterprise AI platform for natural language processing',
    amount: '$500M',
    amountNum: 500,
    round: 'Series D',
    date: '2024-07-01',
    investors: ['PSP Investments', 'NVIDIA', 'Salesforce Ventures', 'Oracle'],
    category: 'Enterprise AI',
    valuation: '$5.5B',
    website: 'https://cohere.com',
    headquarters: 'Toronto, Canada',
  },
  {
    id: 'groq-series-d-2024',
    company: 'Groq',
    description: 'AI inference chip company with LPU architecture for ultra-fast inference',
    amount: '$640M',
    amountNum: 640,
    round: 'Series D',
    date: '2024-08-01',
    investors: ['BlackRock', 'Samsung', 'Cisco', 'Global Founders Capital'],
    category: 'AI Hardware',
    valuation: '$2.8B',
    website: 'https://groq.com',
    headquarters: 'Mountain View, CA',
  },
  {
    id: 'figure-series-b-2024',
    company: 'Figure',
    description: 'Humanoid robotics company building general-purpose robots',
    amount: '$675M',
    amountNum: 675,
    round: 'Series B',
    date: '2024-02-01',
    investors: ['Microsoft', 'NVIDIA', 'OpenAI', 'Jeff Bezos', 'Intel'],
    category: 'Robotics',
    valuation: '$2.6B',
    website: 'https://figure.ai',
    headquarters: 'Sunnyvale, CA',
  },
  {
    id: 'runway-series-c-2024',
    company: 'Runway',
    description: 'AI video generation and editing platform, creator of Gen-3',
    amount: '$141M',
    amountNum: 141,
    round: 'Series C',
    date: '2024-06-01',
    investors: ['General Atlantic', 'Google', 'NVIDIA', 'Salesforce'],
    category: 'AI Applications',
    valuation: '$1.5B',
    website: 'https://runway.ml',
    headquarters: 'New York, NY',
  },
  {
    id: 'glean-series-e-2024',
    company: 'Glean',
    description: 'Enterprise AI search and knowledge management platform',
    amount: '$260M',
    amountNum: 260,
    round: 'Series E',
    date: '2024-09-01',
    investors: ['Altimeter', 'DST Global', 'General Catalyst', 'Kleiner Perkins'],
    category: 'Enterprise AI',
    valuation: '$4.6B',
    website: 'https://glean.com',
    headquarters: 'Palo Alto, CA',
  },
  {
    id: 'harvey-series-c-2024',
    company: 'Harvey',
    description: 'AI platform for law firms and professional services',
    amount: '$100M',
    amountNum: 100,
    round: 'Series C',
    date: '2024-07-01',
    investors: ['Sequoia Capital', 'Google Ventures', 'Kleiner Perkins'],
    category: 'Enterprise AI',
    valuation: '$1.5B',
    website: 'https://harvey.ai',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'inflection-2024',
    company: 'Inflection AI',
    description: 'AI studio building personal AI assistants, creator of Pi',
    amount: '$1.3B',
    amountNum: 1300,
    round: 'Series B',
    date: '2024-01-01',
    investors: ['Microsoft', 'NVIDIA', 'Bill Gates', 'Eric Schmidt'],
    category: 'Foundation Models',
    valuation: '$4B',
    website: 'https://inflection.ai',
    headquarters: 'Palo Alto, CA',
  },
  {
    id: 'cognition-series-a-2024',
    company: 'Cognition',
    description: 'Creator of Devin, the AI software engineer',
    amount: '$175M',
    amountNum: 175,
    round: 'Series A',
    date: '2024-04-01',
    investors: ['Founders Fund', 'a16z', 'Khosla Ventures'],
    category: 'AI Agents',
    valuation: '$2B',
    website: 'https://cognition-labs.com',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'together-series-a-2024',
    company: 'Together AI',
    description: 'Open AI cloud platform for running and fine-tuning models',
    amount: '$106M',
    amountNum: 106,
    round: 'Series A',
    date: '2024-02-01',
    investors: ['Kleiner Perkins', 'NVIDIA', 'Emergence Capital'],
    category: 'AI Infrastructure',
    valuation: '$1.25B',
    website: 'https://together.ai',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'anduril-series-f-2024',
    company: 'Anduril',
    description: 'Defense AI company building autonomous systems',
    amount: '$1.5B',
    amountNum: 1500,
    round: 'Series F',
    date: '2024-08-01',
    investors: ['Founders Fund', 'a16z', 'General Catalyst', 'Valor Equity'],
    category: 'AI Applications',
    valuation: '$14B',
    website: 'https://anduril.com',
    headquarters: 'Costa Mesa, CA',
  },
  {
    id: 'waymo-2024',
    company: 'Waymo',
    description: 'Alphabet\'s autonomous vehicle and robotaxi company',
    amount: '$5.6B',
    amountNum: 5600,
    round: 'Growth',
    date: '2024-10-01',
    investors: ['Alphabet', 'Andreessen Horowitz', 'Fidelity', 'Silver Lake'],
    category: 'Autonomous Vehicles',
    valuation: '$45B',
    website: 'https://waymo.com',
    headquarters: 'Mountain View, CA',
  },
  {
    id: 'imbue-series-b-2024',
    company: 'Imbue',
    description: 'AI research company building agents that reason and code',
    amount: '$200M',
    amountNum: 200,
    round: 'Series B',
    date: '2024-03-01',
    investors: ['NVIDIA', 'Astera Institute', 'a16z'],
    category: 'AI Agents',
    valuation: '$1B',
    website: 'https://imbue.com',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'cursor-series-b-2024',
    company: 'Anysphere (Cursor)',
    description: 'AI-native code editor built for pair programming with AI',
    amount: '$60M',
    amountNum: 60,
    round: 'Series B',
    date: '2024-08-01',
    investors: ['a16z', 'Thrive Capital', 'Spark Capital'],
    category: 'AI Applications',
    valuation: '$400M',
    website: 'https://cursor.sh',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'safe-superintelligence-2024',
    company: 'Safe Superintelligence Inc.',
    description: 'AI safety company founded by Ilya Sutskever focusing on safe superintelligence',
    amount: '$1B',
    amountNum: 1000,
    round: 'Seed',
    date: '2024-09-01',
    investors: ['a16z', 'Sequoia Capital', 'DST Global', 'SV Angel'],
    category: 'AI Safety',
    valuation: '$5B',
    website: 'https://ssi.inc',
    headquarters: 'Palo Alto, CA',
  },
  {
    id: 'poolside-series-a-2024',
    company: 'Poolside',
    description: 'AI company building code generation models for software engineering',
    amount: '$500M',
    amountNum: 500,
    round: 'Series A',
    date: '2024-10-01',
    investors: ['Bain Capital Ventures', 'DST Global', 'Redpoint Ventures'],
    category: 'AI Applications',
    valuation: '$3B',
    website: 'https://poolside.ai',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'reka-series-a-2024',
    company: 'Reka',
    description: 'Multimodal AI lab building state-of-the-art foundation models',
    amount: '$58M',
    amountNum: 58,
    round: 'Series A',
    date: '2024-04-01',
    investors: ['DST Global', 'Radical Ventures', 'Snowflake'],
    category: 'Foundation Models',
    valuation: '$300M',
    website: 'https://reka.ai',
    headquarters: 'London, UK',
  },
  {
    id: 'hippocratic-series-a-2024',
    company: 'Hippocratic AI',
    description: 'Healthcare AI building safety-focused LLMs for medical applications',
    amount: '$53M',
    amountNum: 53,
    round: 'Series A',
    date: '2024-03-01',
    investors: ['General Catalyst', 'a16z', 'Premji Invest'],
    category: 'Healthcare AI',
    valuation: '$500M',
    website: 'https://hippocratic.ai',
    headquarters: 'Palo Alto, CA',
  },
  {
    id: '1x-series-b-2024',
    company: '1X Technologies',
    description: 'Norwegian robotics company building humanoid robots for labor',
    amount: '$100M',
    amountNum: 100,
    round: 'Series B',
    date: '2024-01-01',
    investors: ['EQT Ventures', 'Samsung', 'OpenAI'],
    category: 'Robotics',
    valuation: '$500M',
    website: 'https://1x.tech',
    headquarters: 'Moss, Norway',
  },
  {
    id: 'physical-intelligence-2024',
    company: 'Physical Intelligence',
    description: 'Building foundation models for robotics and physical AI',
    amount: '$400M',
    amountNum: 400,
    round: 'Series A',
    date: '2024-11-01',
    investors: ['Thrive Capital', 'Lux Capital', 'Khosla Ventures', 'OpenAI'],
    category: 'Robotics',
    valuation: '$2B',
    website: 'https://physicalintelligence.company',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'world-labs-2024',
    company: 'World Labs',
    description: 'Fei-Fei Li\'s startup building large world models for spatial intelligence',
    amount: '$230M',
    amountNum: 230,
    round: 'Seed',
    date: '2024-09-01',
    investors: ['a16z', 'NEA', 'Radical Ventures', 'NVIDIA'],
    category: 'Foundation Models',
    valuation: '$1B',
    website: 'https://worldlabs.ai',
    headquarters: 'San Francisco, CA',
  },
  {
    id: 'pika-series-b-2024',
    company: 'Pika',
    description: 'AI video generation platform for creators',
    amount: '$80M',
    amountNum: 80,
    round: 'Series B',
    date: '2024-04-01',
    investors: ['Spark Capital', 'Lightspeed Venture Partners', 'Elad Gil'],
    category: 'AI Applications',
    valuation: '$470M',
    website: 'https://pika.art',
    headquarters: 'Palo Alto, CA',
  },
  {
    id: 'ideogram-series-a-2024',
    company: 'Ideogram',
    description: 'AI image generation with superior text rendering capabilities',
    amount: '$80M',
    amountNum: 80,
    round: 'Series A',
    date: '2024-08-01',
    investors: ['a16z', 'Index Ventures'],
    category: 'AI Applications',
    valuation: '$580M',
    website: 'https://ideogram.ai',
    headquarters: 'Toronto, Canada',
  },
  {
    id: 'sakana-series-a-2024',
    company: 'Sakana AI',
    description: 'Japanese AI lab building nature-inspired foundation models',
    amount: '$100M',
    amountNum: 100,
    round: 'Series A',
    date: '2024-01-01',
    investors: ['Lux Capital', 'Khosla Ventures', 'NVIDIA'],
    category: 'Foundation Models',
    valuation: '$500M',
    website: 'https://sakana.ai',
    headquarters: 'Tokyo, Japan',
  },
];

// Helper functions
export function getFundingByCategory(category: string): FundingRound[] {
  return FUNDING_ROUNDS.filter((round) => round.category === category);
}

export function getFundingByYear(year: number): FundingRound[] {
  return FUNDING_ROUNDS.filter((round) => new Date(round.date).getFullYear() === year);
}

export function getTotalFundingByCategory(): Record<string, number> {
  const totals: Record<string, number> = {};
  FUNDING_ROUNDS.forEach((round) => {
    totals[round.category] = (totals[round.category] || 0) + round.amountNum;
  });
  return totals;
}

export function getTopRounds(limit: number = 10): FundingRound[] {
  return [...FUNDING_ROUNDS].sort((a, b) => b.amountNum - a.amountNum).slice(0, limit);
}

export function getRecentRounds(limit: number = 10): FundingRound[] {
  return [...FUNDING_ROUNDS]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, limit);
}
