// AI Tools Directory Data
// Curated collection of AI tools organized by category

export type AITool = {
  id: string;
  name: string;
  tagline: string;
  description: string;
  url: string;
  category: string;
  subcategory?: string;
  pricing: 'Free' | 'Freemium' | 'Paid' | 'Enterprise' | 'Open Source';
  pricingDetail?: string;
  features: string[];
  useCases: string[];
  company?: string;
  launchDate?: string;
  popular?: boolean;
  trending?: boolean;
};

export const TOOL_CATEGORIES = [
  { id: 'chatbots', name: 'AI Chatbots', icon: 'MessageSquare', description: 'Conversational AI assistants' },
  { id: 'writing', name: 'AI Writing', icon: 'PenTool', description: 'Content generation and editing' },
  { id: 'image', name: 'Image Generation', icon: 'Image', description: 'Create and edit images with AI' },
  { id: 'video', name: 'Video & Animation', icon: 'Video', description: 'AI video creation and editing' },
  { id: 'audio', name: 'Audio & Music', icon: 'Music', description: 'Voice, music, and audio AI' },
  { id: 'code', name: 'AI Coding', icon: 'Code', description: 'Code generation and assistance' },
  { id: 'productivity', name: 'Productivity', icon: 'Zap', description: 'AI-powered workflow tools' },
  { id: 'research', name: 'Research & Analysis', icon: 'Search', description: 'AI research assistants' },
  { id: 'design', name: 'Design & Creative', icon: 'Palette', description: 'AI design tools' },
  { id: 'business', name: 'Business & Marketing', icon: 'Briefcase', description: 'AI for business operations' },
  { id: 'data', name: 'Data & Analytics', icon: 'BarChart', description: 'AI data analysis tools' },
  { id: 'developer', name: 'Developer Tools', icon: 'Terminal', description: 'APIs, SDKs, and dev tools' },
] as const;

export const AI_TOOLS: AITool[] = [
  // AI Chatbots
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'The AI assistant that started it all',
    description: 'OpenAI\'s conversational AI powered by GPT-4. Chat, create content, analyze data, and get help with virtually any task.',
    url: 'https://chat.openai.com',
    category: 'chatbots',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Plus $20/mo, Team $25/user/mo',
    features: ['GPT-4o model', 'Image generation (DALL-E)', 'Code interpreter', 'Web browsing', 'Custom GPTs', 'Voice mode'],
    useCases: ['Writing assistance', 'Code help', 'Research', 'Learning', 'Creative projects'],
    company: 'OpenAI',
    popular: true,
  },
  {
    id: 'claude',
    name: 'Claude',
    tagline: 'Thoughtful AI assistant by Anthropic',
    description: 'Anthropic\'s AI assistant known for nuanced understanding, long context windows, and safety-focused design.',
    url: 'https://claude.ai',
    category: 'chatbots',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $20/mo',
    features: ['200K context window', 'Document analysis', 'Code generation', 'Artifacts (live code)', 'Projects', 'Vision'],
    useCases: ['Long document analysis', 'Coding', 'Writing', 'Research', 'Complex reasoning'],
    company: 'Anthropic',
    popular: true,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    tagline: 'Google\'s multimodal AI',
    description: 'Google\'s AI assistant with deep integration into Google services and strong multimodal capabilities.',
    url: 'https://gemini.google.com',
    category: 'chatbots',
    pricing: 'Freemium',
    pricingDetail: 'Free, Advanced $20/mo with Google One',
    features: ['Google integration', 'Image understanding', 'Code generation', 'Real-time info', '1M token context'],
    useCases: ['Research', 'Google Workspace', 'Coding', 'Creative writing'],
    company: 'Google',
    popular: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    tagline: 'AI-powered answer engine',
    description: 'Search engine meets AI. Get cited answers with real-time web access and academic sources.',
    url: 'https://perplexity.ai',
    category: 'chatbots',
    subcategory: 'Search',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $20/mo',
    features: ['Real-time search', 'Source citations', 'Academic search', 'Focus modes', 'Collections'],
    useCases: ['Research', 'Fact-checking', 'Learning', 'News', 'Academic work'],
    company: 'Perplexity AI',
    popular: true,
    trending: true,
  },
  {
    id: 'poe',
    name: 'Poe',
    tagline: 'Access all AI models in one place',
    description: 'Quora\'s AI platform offering access to GPT-4, Claude, Llama, and more in one interface.',
    url: 'https://poe.com',
    category: 'chatbots',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Subscription $20/mo',
    features: ['Multiple models', 'Custom bots', 'Bot creation', 'Knowledge bases'],
    useCases: ['Model comparison', 'Custom assistants', 'Research'],
    company: 'Quora',
  },

  // AI Writing
  {
    id: 'jasper',
    name: 'Jasper',
    tagline: 'AI marketing content platform',
    description: 'Enterprise AI platform for marketing teams. Generate on-brand content at scale.',
    url: 'https://jasper.ai',
    category: 'writing',
    pricing: 'Paid',
    pricingDetail: 'Creator $49/mo, Pro $69/mo',
    features: ['Brand voice', 'Templates', 'SEO optimization', 'Team collaboration', 'Chrome extension'],
    useCases: ['Marketing copy', 'Blog posts', 'Social media', 'Ad copy', 'Email'],
    company: 'Jasper AI',
    popular: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    tagline: 'AI-powered copywriting',
    description: 'Generate marketing copy, blog content, and more with AI assistance.',
    url: 'https://copy.ai',
    category: 'writing',
    pricing: 'Freemium',
    pricingDetail: 'Free 2000 words/mo, Pro $49/mo',
    features: ['90+ templates', 'Workflows', 'Brand voice', 'Team features'],
    useCases: ['Marketing copy', 'Product descriptions', 'Social posts', 'Emails'],
    company: 'Copy.ai',
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    tagline: 'AI writing assistant',
    description: 'Real-time grammar, spelling, and style suggestions powered by AI.',
    url: 'https://grammarly.com',
    category: 'writing',
    subcategory: 'Editing',
    pricing: 'Freemium',
    pricingDetail: 'Free basic, Premium $12/mo',
    features: ['Grammar check', 'Tone detection', 'Plagiarism check', 'GrammarlyGO AI', 'Browser extension'],
    useCases: ['Email writing', 'Documents', 'Academic writing', 'Professional communication'],
    company: 'Grammarly',
    popular: true,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    tagline: 'AI writing in your workspace',
    description: 'AI writing and editing built into Notion. Summarize, brainstorm, and draft within your notes.',
    url: 'https://notion.so/product/ai',
    category: 'writing',
    subcategory: 'Productivity',
    pricing: 'Paid',
    pricingDetail: '$10/member/mo add-on',
    features: ['Summarization', 'Translation', 'Brainstorming', 'Action items', 'Native integration'],
    useCases: ['Note-taking', 'Documentation', 'Meeting notes', 'Project planning'],
    company: 'Notion',
    popular: true,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    tagline: 'AI writer for blogs and marketing',
    description: 'Create SEO-optimized blog posts, ads, and marketing content with AI.',
    url: 'https://writesonic.com',
    category: 'writing',
    pricing: 'Freemium',
    pricingDetail: 'Free trial, Pro from $16/mo',
    features: ['Article writer', 'Chatsonic', 'Brand voice', 'Fact-checking', 'SEO'],
    useCases: ['Blog writing', 'SEO content', 'Product descriptions', 'Ads'],
  },

  // Image Generation
  {
    id: 'midjourney',
    name: 'Midjourney',
    tagline: 'Stunning AI art generation',
    description: 'Create breathtaking artwork and images through Discord. Known for aesthetic, artistic outputs.',
    url: 'https://midjourney.com',
    category: 'image',
    pricing: 'Paid',
    pricingDetail: 'Basic $10/mo, Standard $30/mo',
    features: ['Discord-based', 'High quality', 'Style variations', 'Upscaling', 'Web interface (alpha)'],
    useCases: ['Art creation', 'Concept art', 'Marketing visuals', 'Creative projects'],
    company: 'Midjourney',
    popular: true,
  },
  {
    id: 'dall-e',
    name: 'DALL-E 3',
    tagline: 'OpenAI\'s image generator',
    description: 'Generate images from text descriptions. Integrated into ChatGPT and available via API.',
    url: 'https://openai.com/dall-e-3',
    category: 'image',
    pricing: 'Freemium',
    pricingDetail: 'Via ChatGPT Plus or API',
    features: ['Text rendering', 'ChatGPT integration', 'Prompt rewriting', 'High accuracy'],
    useCases: ['Marketing images', 'Social media', 'Illustrations', 'Prototyping'],
    company: 'OpenAI',
    popular: true,
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    tagline: 'Open source image generation',
    description: 'Open source AI image generation. Run locally or use hosted versions. Highly customizable.',
    url: 'https://stability.ai',
    category: 'image',
    pricing: 'Open Source',
    pricingDetail: 'Free to run locally, hosted versions vary',
    features: ['Open source', 'Local running', 'LoRA fine-tuning', 'ControlNet', 'Huge community'],
    useCases: ['Art', 'Fine-tuned models', 'Custom pipelines', 'Research'],
    company: 'Stability AI',
    popular: true,
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    tagline: 'AI images with perfect text',
    description: 'Generate images with accurate text rendering. Perfect for posters, logos, and typography.',
    url: 'https://ideogram.ai',
    category: 'image',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Plus $8/mo',
    features: ['Text rendering', 'Logo design', 'Poster creation', 'Style presets'],
    useCases: ['Logos', 'Posters', 'Marketing', 'Social graphics'],
    trending: true,
  },
  {
    id: 'leonardo',
    name: 'Leonardo.ai',
    tagline: 'AI image generation platform',
    description: 'Create production-quality visual assets for games, marketing, and creative projects.',
    url: 'https://leonardo.ai',
    category: 'image',
    pricing: 'Freemium',
    pricingDetail: 'Free 150 tokens/day, from $12/mo',
    features: ['Fine-tuned models', 'Canvas editor', 'Real-time gen', 'Game assets', 'Consistency'],
    useCases: ['Game assets', 'Marketing', 'Character design', 'Product shots'],
  },
  {
    id: 'remove-bg',
    name: 'Remove.bg',
    tagline: 'AI background removal',
    description: 'Remove image backgrounds instantly with AI. One-click and API available.',
    url: 'https://remove.bg',
    category: 'image',
    subcategory: 'Editing',
    pricing: 'Freemium',
    pricingDetail: 'Free low-res, credits from $9',
    features: ['One-click removal', 'API', 'Bulk processing', 'Photoshop plugin'],
    useCases: ['Product photos', 'Portraits', 'E-commerce', 'Design'],
  },

  // Video & Animation
  {
    id: 'runway',
    name: 'Runway',
    tagline: 'AI video generation & editing',
    description: 'Create and edit videos with AI. Gen-3 Alpha produces stunning video from text.',
    url: 'https://runway.ml',
    category: 'video',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Standard $15/mo',
    features: ['Gen-3 video', 'Text to video', 'Image to video', 'Video editing', 'Green screen'],
    useCases: ['Video production', 'Social content', 'Film', 'Advertising'],
    company: 'Runway',
    popular: true,
    trending: true,
  },
  {
    id: 'pika',
    name: 'Pika',
    tagline: 'AI video creation made easy',
    description: 'Generate and edit videos with AI. Turn ideas into videos quickly.',
    url: 'https://pika.art',
    category: 'video',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro from $8/mo',
    features: ['Text to video', 'Image to video', 'Video editing', 'Lip sync'],
    useCases: ['Social videos', 'Marketing', 'Creative projects'],
    trending: true,
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    tagline: 'AI video generation with avatars',
    description: 'Create professional videos with AI avatars. Perfect for training, marketing, and sales.',
    url: 'https://heygen.com',
    category: 'video',
    pricing: 'Freemium',
    pricingDetail: 'Free trial, Creator $29/mo',
    features: ['AI avatars', '300+ voices', 'Custom avatars', 'Templates', 'Translations'],
    useCases: ['Training videos', 'Sales videos', 'Marketing', 'Localization'],
    popular: true,
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    tagline: 'AI video creation platform',
    description: 'Create videos with AI avatars from text. Enterprise-focused with 160+ avatars.',
    url: 'https://synthesia.io',
    category: 'video',
    pricing: 'Paid',
    pricingDetail: 'Starter $29/mo, Enterprise custom',
    features: ['160+ avatars', '130+ languages', 'Custom avatars', 'Screen recording', 'Templates'],
    useCases: ['Corporate training', 'Product demos', 'HR', 'Marketing'],
    company: 'Synthesia',
  },
  {
    id: 'descript',
    name: 'Descript',
    tagline: 'AI-powered video & podcast editing',
    description: 'Edit video and audio by editing text. AI removes filler words, fixes eye contact, and more.',
    url: 'https://descript.com',
    category: 'video',
    subcategory: 'Editing',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $24/mo',
    features: ['Text-based editing', 'Filler word removal', 'Eye contact fix', 'Overdub voice', 'Screen recording'],
    useCases: ['Podcasts', 'YouTube', 'Corporate video', 'Social content'],
    popular: true,
  },

  // Audio & Music
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    tagline: 'Realistic AI voice generation',
    description: 'Generate human-like speech in any voice. Clone voices, create audiobooks, and more.',
    url: 'https://elevenlabs.io',
    category: 'audio',
    pricing: 'Freemium',
    pricingDetail: 'Free 10K chars/mo, from $5/mo',
    features: ['Voice cloning', '29 languages', 'Projects', 'API', 'Real-time streaming'],
    useCases: ['Audiobooks', 'Voice-over', 'Content creation', 'Accessibility'],
    company: 'ElevenLabs',
    popular: true,
    trending: true,
  },
  {
    id: 'suno',
    name: 'Suno',
    tagline: 'AI music generation',
    description: 'Create full songs with vocals from text prompts. Make music without instruments.',
    url: 'https://suno.com',
    category: 'audio',
    subcategory: 'Music',
    pricing: 'Freemium',
    pricingDetail: 'Free 10 songs/day, Pro $10/mo',
    features: ['Text to song', 'Vocals', 'Custom lyrics', 'Instrumentals', 'Covers'],
    useCases: ['Music creation', 'Content soundtracks', 'Fun', 'Prototyping'],
    popular: true,
    trending: true,
  },
  {
    id: 'udio',
    name: 'Udio',
    tagline: 'AI music composition',
    description: 'Generate high-quality music tracks from text descriptions. Create any genre.',
    url: 'https://udio.com',
    category: 'audio',
    subcategory: 'Music',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Standard $10/mo',
    features: ['Text to music', 'Genre variety', 'Extensions', 'Remixing'],
    useCases: ['Music production', 'Content creation', 'Soundtracks'],
    trending: true,
  },
  {
    id: 'murf',
    name: 'Murf',
    tagline: 'AI voice over studio',
    description: 'Professional AI voices for videos, presentations, and more. 120+ voices.',
    url: 'https://murf.ai',
    category: 'audio',
    pricing: 'Freemium',
    pricingDetail: 'Free trial, Basic $29/mo',
    features: ['120+ voices', 'Voice cloning', 'Video sync', 'API', 'Collaboration'],
    useCases: ['Voice-over', 'E-learning', 'Advertising', 'Explainers'],
  },

  // AI Coding
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    tagline: 'AI pair programmer',
    description: 'AI code completion and generation in your IDE. Trained on billions of lines of code.',
    url: 'https://github.com/features/copilot',
    category: 'code',
    pricing: 'Paid',
    pricingDetail: 'Individual $10/mo, Business $19/user/mo',
    features: ['Code completion', 'Chat', 'Documentation', 'Test generation', 'Multi-IDE'],
    useCases: ['Coding', 'Learning', 'Documentation', 'Testing'],
    company: 'GitHub/Microsoft',
    popular: true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'AI-native code editor',
    description: 'VS Code fork built for AI-first coding. Chat with your codebase, generate and edit code.',
    url: 'https://cursor.sh',
    category: 'code',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $20/mo',
    features: ['Codebase chat', 'Multi-file editing', 'Composer', 'Tab completion', 'Multiple models'],
    useCases: ['Software development', 'Refactoring', 'Learning', 'Debugging'],
    company: 'Anysphere',
    popular: true,
    trending: true,
  },
  {
    id: 'replit-ai',
    name: 'Replit AI',
    tagline: 'AI-powered coding in browser',
    description: 'Code with AI in a browser-based IDE. Generate apps, debug, and deploy instantly.',
    url: 'https://replit.com',
    category: 'code',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $25/mo',
    features: ['Browser IDE', 'AI chat', 'Ghost Writer', 'Deployments', 'Multiplayer'],
    useCases: ['Learning to code', 'Prototyping', 'Collaboration', 'Deployment'],
    company: 'Replit',
    popular: true,
  },
  {
    id: 'codeium',
    name: 'Codeium',
    tagline: 'Free AI code completion',
    description: 'Free AI coding assistant with autocomplete and chat. Supports 70+ languages.',
    url: 'https://codeium.com',
    category: 'code',
    pricing: 'Freemium',
    pricingDetail: 'Free for individuals, Teams $12/user/mo',
    features: ['Code completion', 'Chat', '70+ languages', 'Multi-IDE', 'Self-hosted option'],
    useCases: ['Coding', 'Learning', 'All IDE users'],
    company: 'Codeium',
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    tagline: 'AI code assistant',
    description: 'AI-powered code completion with privacy-first design. Runs locally.',
    url: 'https://tabnine.com',
    category: 'code',
    pricing: 'Freemium',
    pricingDetail: 'Free basic, Pro $12/mo',
    features: ['Local processing', 'Privacy-first', 'Code completion', 'Team learning'],
    useCases: ['Enterprise coding', 'Privacy-sensitive projects'],
    company: 'Tabnine',
  },
  {
    id: 'v0',
    name: 'v0 by Vercel',
    tagline: 'AI UI generation',
    description: 'Generate React/Next.js UI components from text descriptions. Ship faster.',
    url: 'https://v0.dev',
    category: 'code',
    subcategory: 'UI',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Premium $20/mo',
    features: ['React generation', 'Tailwind CSS', 'shadcn/ui', 'Iterations', 'Export code'],
    useCases: ['Frontend dev', 'Prototyping', 'UI design'],
    company: 'Vercel',
    trending: true,
  },

  // Productivity
  {
    id: 'otter',
    name: 'Otter.ai',
    tagline: 'AI meeting notes',
    description: 'Automatic meeting transcription and notes. Joins calls and captures everything.',
    url: 'https://otter.ai',
    category: 'productivity',
    pricing: 'Freemium',
    pricingDetail: 'Free 300 mins/mo, Pro $16.99/mo',
    features: ['Auto transcription', 'Meeting summaries', 'Speaker ID', 'Zoom/Teams/Meet', 'Search'],
    useCases: ['Meetings', 'Interviews', 'Lectures', 'Accessibility'],
    popular: true,
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    tagline: 'AI meeting assistant',
    description: 'Transcribe, summarize, and search across meetings. Integrates with major platforms.',
    url: 'https://fireflies.ai',
    category: 'productivity',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $18/mo',
    features: ['Transcription', 'AI summaries', 'Action items', 'CRM integration', 'Analytics'],
    useCases: ['Sales calls', 'Team meetings', 'Interviews'],
  },
  {
    id: 'motion',
    name: 'Motion',
    tagline: 'AI calendar & task manager',
    description: 'AI automatically schedules your tasks and meetings for optimal productivity.',
    url: 'https://usemotion.com',
    category: 'productivity',
    pricing: 'Paid',
    pricingDetail: 'Individual $34/mo, Team $20/user/mo',
    features: ['Auto-scheduling', 'Task management', 'Calendar blocking', 'Project planning', 'Booking'],
    useCases: ['Time management', 'Scheduling', 'Project planning'],
    popular: true,
  },
  {
    id: 'zapier-ai',
    name: 'Zapier AI',
    tagline: 'AI automation builder',
    description: 'Create automations with natural language. Connect 6000+ apps with AI assistance.',
    url: 'https://zapier.com',
    category: 'productivity',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, from $29.99/mo',
    features: ['Natural language', '6000+ apps', 'AI actions', 'Chatbots', 'Tables'],
    useCases: ['Workflow automation', 'Integration', 'Data processing'],
    company: 'Zapier',
  },

  // Research & Analysis
  {
    id: 'elicit',
    name: 'Elicit',
    tagline: 'AI research assistant',
    description: 'Find and summarize academic papers. Extract data and synthesize findings with AI.',
    url: 'https://elicit.com',
    category: 'research',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Plus $10/mo',
    features: ['Paper search', 'Summarization', 'Data extraction', 'Literature review', 'Citations'],
    useCases: ['Academic research', 'Literature review', 'Systematic reviews'],
    popular: true,
  },
  {
    id: 'consensus',
    name: 'Consensus',
    tagline: 'AI-powered science search',
    description: 'Search 200M+ scientific papers with AI. Get evidence-based answers.',
    url: 'https://consensus.app',
    category: 'research',
    pricing: 'Freemium',
    pricingDetail: 'Free basic, Premium $9.99/mo',
    features: ['Paper search', 'Consensus meter', 'Citations', 'Copilot synthesis'],
    useCases: ['Research', 'Fact-checking', 'Academic writing'],
  },
  {
    id: 'scite',
    name: 'scite',
    tagline: 'Smart citations',
    description: 'See how papers cite each other. Find supporting or contrasting evidence.',
    url: 'https://scite.ai',
    category: 'research',
    pricing: 'Freemium',
    pricingDetail: 'Free basic, Premium from $20/mo',
    features: ['Smart citations', 'Citation context', 'Reference check', 'AI assistant'],
    useCases: ['Citation analysis', 'Literature review', 'Research validation'],
  },
  {
    id: 'semantic-scholar',
    name: 'Semantic Scholar',
    tagline: 'AI-powered research search',
    description: 'Free AI research tool from Allen Institute. Search 200M+ papers with semantic understanding.',
    url: 'https://semanticscholar.org',
    category: 'research',
    pricing: 'Free',
    features: ['Semantic search', 'Paper recommendations', 'TLDR summaries', 'Citation graphs', 'API'],
    useCases: ['Academic research', 'Paper discovery', 'Citation tracking'],
  },

  // Design & Creative
  {
    id: 'canva-ai',
    name: 'Canva AI',
    tagline: 'AI design made simple',
    description: 'Generate images, edit photos, and create designs with AI in Canva.',
    url: 'https://canva.com',
    category: 'design',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $15/mo',
    features: ['Magic Design', 'Text to image', 'Background remover', 'Magic Write', 'Magic Edit'],
    useCases: ['Social graphics', 'Presentations', 'Marketing', 'Documents'],
    company: 'Canva',
    popular: true,
  },
  {
    id: 'figma-ai',
    name: 'Figma AI',
    tagline: 'AI-powered design in Figma',
    description: 'Generate designs, rename layers, remove backgrounds, and more with AI in Figma.',
    url: 'https://figma.com',
    category: 'design',
    pricing: 'Freemium',
    pricingDetail: 'Included in Figma plans',
    features: ['Visual search', 'Auto rename', 'Background removal', 'First Draft', 'Rewrite'],
    useCases: ['UI design', 'Prototyping', 'Design systems'],
    company: 'Figma',
    popular: true,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    tagline: 'Adobe\'s generative AI',
    description: 'Generate images, text effects, and designs. Trained on licensed content for commercial use.',
    url: 'https://firefly.adobe.com',
    category: 'design',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Premium with CC subscription',
    features: ['Text to image', 'Generative fill', 'Text effects', 'Commercial safe', 'CC integration'],
    useCases: ['Photo editing', 'Marketing', 'Design', 'Creative projects'],
    company: 'Adobe',
    popular: true,
  },
  {
    id: 'photoroom',
    name: 'PhotoRoom',
    tagline: 'AI photo editor',
    description: 'Remove backgrounds, create product photos, and edit images with AI.',
    url: 'https://photoroom.com',
    category: 'design',
    subcategory: 'Photo Editing',
    pricing: 'Freemium',
    pricingDetail: 'Free with watermark, Pro $12.99/mo',
    features: ['Background removal', 'Product photos', 'Batch editing', 'Templates', 'API'],
    useCases: ['E-commerce', 'Product photography', 'Social media'],
  },

  // Business & Marketing
  {
    id: 'hubspot-ai',
    name: 'HubSpot AI',
    tagline: 'AI for CRM and marketing',
    description: 'AI tools built into HubSpot for content, customer insights, and automation.',
    url: 'https://hubspot.com',
    category: 'business',
    pricing: 'Freemium',
    pricingDetail: 'Included in HubSpot plans',
    features: ['Content assistant', 'ChatSpot', 'Predictive lead scoring', 'AI email', 'Reporting'],
    useCases: ['Marketing', 'Sales', 'Customer service', 'CRM'],
    company: 'HubSpot',
  },
  {
    id: 'salesforce-einstein',
    name: 'Salesforce Einstein',
    tagline: 'AI for Salesforce CRM',
    description: 'AI predictions, recommendations, and automation across Salesforce products.',
    url: 'https://salesforce.com/einstein',
    category: 'business',
    pricing: 'Enterprise',
    pricingDetail: 'Included in certain Salesforce editions',
    features: ['Predictive scoring', 'Einstein GPT', 'Recommendations', 'Automation', 'Analytics'],
    useCases: ['Sales', 'Service', 'Marketing', 'Commerce'],
    company: 'Salesforce',
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    tagline: 'AI presentation maker',
    description: 'Create beautiful presentations with AI-powered design. Smart templates adapt as you type.',
    url: 'https://beautiful.ai',
    category: 'business',
    subcategory: 'Presentations',
    pricing: 'Paid',
    pricingDetail: 'Pro $12/mo, Team $40/user/mo',
    features: ['Smart templates', 'Auto-design', 'Team library', 'Export options', 'AI content'],
    useCases: ['Business presentations', 'Pitch decks', 'Reports'],
  },

  // Data & Analytics
  {
    id: 'julius',
    name: 'Julius',
    tagline: 'AI data analyst',
    description: 'Chat with your data. Upload files and get instant analysis, visualizations, and insights.',
    url: 'https://julius.ai',
    category: 'data',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $20/mo',
    features: ['Natural language queries', 'Visualizations', 'File upload', 'Python/R code', 'Reports'],
    useCases: ['Data analysis', 'Reporting', 'Business intelligence'],
    trending: true,
  },
  {
    id: 'obviously-ai',
    name: 'Obviously AI',
    tagline: 'No-code ML predictions',
    description: 'Build predictive models without code. Upload data and get predictions in minutes.',
    url: 'https://obviously.ai',
    category: 'data',
    pricing: 'Paid',
    pricingDetail: 'From $75/mo',
    features: ['AutoML', 'Predictions', 'Integrations', 'APIs', 'Time series'],
    useCases: ['Sales forecasting', 'Churn prediction', 'Lead scoring'],
  },

  // Developer Tools
  {
    id: 'langchain',
    name: 'LangChain',
    tagline: 'Build LLM applications',
    description: 'Framework for developing applications powered by language models. Chains, agents, and RAG.',
    url: 'https://langchain.com',
    category: 'developer',
    pricing: 'Open Source',
    pricingDetail: 'Free, LangSmith from $39/mo',
    features: ['Chains', 'Agents', 'RAG', 'Memory', 'Integrations', 'LangSmith observability'],
    useCases: ['LLM apps', 'Chatbots', 'Agents', 'RAG systems'],
    popular: true,
  },
  {
    id: 'llamaindex',
    name: 'LlamaIndex',
    tagline: 'Data framework for LLMs',
    description: 'Connect LLMs to your data. Build RAG applications and knowledge assistants.',
    url: 'https://llamaindex.ai',
    category: 'developer',
    pricing: 'Open Source',
    pricingDetail: 'Free, Cloud offering available',
    features: ['Data connectors', 'Indexing', 'Query engines', 'Agents', 'RAG'],
    useCases: ['RAG', 'Knowledge bases', 'Document Q&A'],
    popular: true,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    tagline: 'The AI community platform',
    description: 'Host models, datasets, and apps. The GitHub of machine learning.',
    url: 'https://huggingface.co',
    category: 'developer',
    pricing: 'Freemium',
    pricingDetail: 'Free tier, Pro $9/mo, Enterprise custom',
    features: ['Model hub', 'Datasets', 'Spaces', 'Inference API', 'Transformers library'],
    useCases: ['Model hosting', 'Fine-tuning', 'Inference', 'Community'],
    company: 'Hugging Face',
    popular: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    tagline: 'Run ML models in the cloud',
    description: 'Run open source models with one line of code. Pay per use.',
    url: 'https://replicate.com',
    category: 'developer',
    pricing: 'Freemium',
    pricingDetail: 'Pay per use, some free credits',
    features: ['One-line API', 'Open models', 'Fine-tuning', 'Deployments'],
    useCases: ['Model inference', 'Prototyping', 'Production apps'],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    tagline: 'Run LLMs locally',
    description: 'Run Llama, Mistral, and other open models on your machine. Simple CLI.',
    url: 'https://ollama.ai',
    category: 'developer',
    pricing: 'Open Source',
    features: ['Local running', 'Multiple models', 'Simple CLI', 'API', 'Customization'],
    useCases: ['Local development', 'Privacy', 'Experimentation'],
    popular: true,
  },
];

// Helper functions
export function getToolsByCategory(category: string): AITool[] {
  return AI_TOOLS.filter((tool) => tool.category === category);
}

export function getPopularTools(): AITool[] {
  return AI_TOOLS.filter((tool) => tool.popular);
}

export function getTrendingTools(): AITool[] {
  return AI_TOOLS.filter((tool) => tool.trending);
}

export function getFreeTools(): AITool[] {
  return AI_TOOLS.filter((tool) => tool.pricing === 'Free' || tool.pricing === 'Open Source');
}

export function searchTools(query: string): AITool[] {
  const q = query.toLowerCase();
  return AI_TOOLS.filter(
    (tool) =>
      tool.name.toLowerCase().includes(q) ||
      tool.tagline.toLowerCase().includes(q) ||
      tool.description.toLowerCase().includes(q) ||
      tool.features.some((f) => f.toLowerCase().includes(q)) ||
      tool.useCases.some((u) => u.toLowerCase().includes(q))
  );
}
